//! Linker setup for the `sonde-usb` binary.
//!
//! `cargo:rustc-link-arg-bins` does not propagate from a dependency's build
//! script, so each binary crate must place `memory.x` on the link search path and
//! pass the linker scripts itself. The decoder name tables are generated by the
//! `sonde-common` library's own `build.rs`; this crate only handles linking.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    // memory.x lives with the shared crate (firmware/common/memory.x); this crate
    // is firmware/usb, so it is one directory up and over.
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("../common/memory.x"))
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=../common/memory.x");
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}
