//! External-flash asset image: OUI / Company-ID / UUID-name lookup tables.
//!
//! The bulk name data for the big tables lives in the on-board 2 MB QSPI flash,
//! memory-mapped (XIP) at `0x1200_0000`, and is streamed there by the host
//! `builder provision` subcommand (see the `provision` task in `main.rs`). Only
//! small search structures stay in internal flash: the OUI alphabet/dictionary,
//! the list of subdivided OUI blocks, and, for every table, a sparse
//! `(key, offset)` checkpoint index generated by `build.rs`.
//!
//! Image layout (byte offsets from the XIP base):
//!   0                 header  `{magic:u32, len:u32, crc:u32}`  (written LAST)
//!   HDR_SIZE          OUI section      (BPE blob, keyed by 24-bit OUI)
//!   OUISUB_XIP_OFF    Long-prefix OUI  (BPE blob, MA-M + MA-S + IAB)
//!   COMPANY_XIP_OFF   Company section  (packed `(u16,name)` records)
//!   UUID_XIP_OFF      UUID section     (packed `(u16,name)` records)
//!
//! Every section is a run of records `[Δkey varint][u8 len][bytes]`, with Δkey
//! resetting to 0 at each 64-record block so a block decodes from its index
//! checkpoint alone. Lookups binary-search the internal index to a block, then
//! scan ≤64 records in the XIP section. Nothing is allocated.
//!
//! IEEE subdivides some 24-bit OUI blocks into 28-bit (MA-M) or 36-bit (MA-S,
//! IAB) assignments, which the MA-L registry lists under the placeholder name
//! "IEEE Registration Authority". Those finer assignments share one section
//! keyed by `(parent ordinal << 12) | extension`, where the ordinal is the
//! block's position in `OUI_SUB_PARENTS`; a bare 36-bit prefix would not fit a
//! `u32`, and the ordinal also keeps records dense so the deltas stay one byte.

use core::slice;
use core::sync::atomic::{AtomicBool, Ordering};

// Internal search structures + image metadata, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/oui_table.rs")); // OUI_ALPHABET/OUI_DICT/OUI_INDEX
include!(concat!(env!("OUT_DIR"), "/company_index.rs")); // COMPANY_INDEX
include!(concat!(env!("OUT_DIR"), "/uuid_index.rs")); // UUID_INDEX
include!(concat!(env!("OUT_DIR"), "/asset_meta.rs")); // ASSET_MAGIC/HDR_SIZE/*_XIP_OFF/*_LEN/…

/// Base of the QSPI memory-mapped (XIP) window.
const XIP: usize = 0x1200_0000;

/// Records per sparse-index block — must match `BLOCK` in build.rs.
const BLOCK: usize = 64;

/// Set once `header_check` confirms a valid image is present in external flash.
/// While false (unprovisioned device) all lookups return `None` and the decoder
/// falls back to raw ids/hex.
static ASSET_READY: AtomicBool = AtomicBool::new(false);

/// Set by the provisioning task while it is erasing/writing external flash, so
/// concurrent lookups don't read a half-written image between CDC packets.
static PROVISIONING: AtomicBool = AtomicBool::new(false);

/// Gate provisioning on/off around an erase+write sequence.
pub fn set_provisioning(on: bool) {
    PROVISIONING.store(on, Ordering::Release);
}

/// Read the image header from XIP and mark the tables available iff the magic
/// and length match what this firmware was built against. Integrity of the body
/// is guaranteed by the header-last write during provisioning, so no full CRC is
/// needed at boot. The caller must have activated the QSPI peripheral (XIP
/// mapped) before calling.
pub fn header_check() {
    // Safety: XIP window is mapped once the QSPI peripheral is active; the header
    // occupies the first HDR_SIZE bytes.
    let hdr = unsafe { slice::from_raw_parts(XIP as *const u8, HDR_SIZE as usize) };
    let magic = u32::from_le_bytes([hdr[0], hdr[1], hdr[2], hdr[3]]);
    let len = u32::from_le_bytes([hdr[4], hdr[5], hdr[6], hdr[7]]);
    let ok = magic == ASSET_MAGIC && len == ASSET_LEN;
    ASSET_READY.store(ok, Ordering::Release);
}

/// Whether a valid asset image is present (set by the last `header_check`).
pub fn is_ready() -> bool {
    ASSET_READY.load(Ordering::Acquire)
}

/// Borrow a section of the asset image as a `'static` slice into XIP, or `None`
/// when no valid image is available (unprovisioned, or mid-provision).
fn section(off: u32, len: u32) -> Option<&'static [u8]> {
    if !ASSET_READY.load(Ordering::Acquire) || PROVISIONING.load(Ordering::Acquire) {
        return None;
    }
    // Safety: XIP memory is valid for 'static once mapped and ASSET_READY is set;
    // [off, off+len) lies within the provisioned image (bounds fixed by build.rs).
    Some(unsafe { slice::from_raw_parts((XIP + off as usize) as *const u8, len as usize) })
}

/// Look up a Bluetooth SIG Company Identifier name. `None` if unassigned or the
/// device is unprovisioned.
pub fn company_name(id: u16) -> Option<&'static str> {
    str_lookup(COMPANY_INDEX, COMPANY_XIP_OFF, COMPANY_LEN, id)
}

/// Look up a 16-bit service/member/SDO UUID name. `None` if unassigned or the
/// device is unprovisioned.
pub fn uuid_name(id: u16) -> Option<&'static str> {
    str_lookup(UUID_INDEX, UUID_XIP_OFF, UUID_LEN, id)
}

/// Binary-search a packed `(u16, name)` section for `key`, returning the name as
/// a `'static` slice into XIP. `index` is the section's sparse checkpoint index.
fn str_lookup(
    index: &[(u16, u32)],
    sec_off: u32,
    sec_len: u32,
    key: u16,
) -> Option<&'static str> {
    let sec = section(sec_off, sec_len)?;
    if index.is_empty() || key < index[0].0 {
        return None;
    }
    // Largest index checkpoint whose starting key is <= the target.
    let mut lo = 0usize;
    let mut hi = index.len() - 1;
    let mut blk = 0usize;
    while lo <= hi {
        let mid = (lo + hi) / 2;
        if index[mid].0 <= key {
            blk = mid;
            lo = mid + 1;
        } else if mid == 0 {
            break;
        } else {
            hi = mid - 1;
        }
    }

    let mut off = index[blk].1 as usize;
    let mut cur = index[blk].0 as u32; // block base; the first record's Δ is 0
    let target = key as u32;
    for _ in 0..BLOCK {
        if off >= sec.len() {
            break;
        }
        let (delta, n) = read_varint(sec, off);
        off += n;
        cur = cur.wrapping_add(delta);
        let len = sec[off] as usize;
        off += 1;
        let bytes = sec.get(off..off + len)?;
        off += len;
        if cur == target {
            return core::str::from_utf8(bytes).ok();
        }
        if cur > target {
            return None; // records are ascending — past the target
        }
    }
    None
}

/// Look up the IEEE vendor organisation name for a MAC. `prefix` is the 24-bit
/// OUI (the top three octets); `ext12` is the 12 bits immediately below it —
/// `((m[3] << 4) | (m[4] >> 4))` for a MAC in display order — which resolves the
/// assignee when IEEE has subdivided that OUI into MA-M or MA-S/IAB blocks.
/// Callers holding fewer than five octets pass `None` and get the block holder.
///
/// Returns the org name in a stack buffer, `None` if unassigned or the device is
/// unprovisioned.
pub fn oui_vendor(prefix: u32, ext12: Option<u16>) -> Option<heapless::String<96>> {
    let mal = scan_bpe_section(OUI_XIP_OFF, OUI_LEN, OUI_INDEX, prefix);

    // A subdivided block names the registrar, not the assignee, so try the
    // long-prefix table whenever the OUI is one of the carved-up ones and the
    // caller supplied the extension bits.
    if let (Some(ext), Ok(ordinal)) = (ext12, OUI_SUB_PARENTS.binary_search(&prefix)) {
        // MA-S and IAB carve a block into 4096; MA-M into 16, keyed by the top
        // 4 of the 12 extension bits.
        let ext = if OUI_SUB36.contains(&prefix) { ext as u32 } else { (ext >> 8) as u32 };
        let key = (ordinal as u32) << 12 | ext;
        if let Some(name) = scan_bpe_section(OUISUB_XIP_OFF, OUISUB_LEN, OUI_SUB_INDEX, key) {
            return Some(name);
        }
    }
    mal
}

/// Binary-search a BPE-packed section for `key` and expand the matching record.
/// `index` is the section's sparse checkpoint index: the search narrows to a
/// block, then scans up to `BLOCK` records from that checkpoint.
fn scan_bpe_section(
    sec_off: u32,
    sec_len: u32,
    index: &[(u32, u32)],
    key: u32,
) -> Option<heapless::String<96>> {
    let blob = section(sec_off, sec_len)?;
    if index.is_empty() || key < index[0].0 {
        return None;
    }
    // Largest index checkpoint whose starting key is <= the target.
    let mut lo = 0usize;
    let mut hi = index.len() - 1;
    let mut blk = 0usize;
    while lo <= hi {
        let mid = (lo + hi) / 2;
        if index[mid].0 <= key {
            blk = mid;
            lo = mid + 1;
        } else if mid == 0 {
            break;
        } else {
            hi = mid - 1;
        }
    }

    let mut off = index[blk].1 as usize;
    let mut cur = index[blk].0; // block base; the first record's Δ is 0
    for _ in 0..BLOCK {
        if off >= blob.len() {
            break;
        }
        let (delta, n) = read_varint(blob, off);
        off += n;
        cur = cur.wrapping_add(delta);
        let enclen = blob[off] as usize;
        off += 1;
        let enc = blob.get(off..off + enclen)?;
        off += enclen;
        if cur == key {
            return Some(expand(enc));
        }
        if cur > key {
            return None; // records are ascending — past the target
        }
    }
    None
}

/// Read an LEB128 varint at `off`, returning `(value, bytes_consumed)`.
fn read_varint(b: &[u8], off: usize) -> (u32, usize) {
    let mut x = 0u32;
    let mut shift = 0;
    let mut i = off;
    loop {
        let byte = b[i];
        i += 1;
        x |= ((byte & 0x7F) as u32) << shift;
        if byte & 0x80 == 0 {
            break;
        }
        shift += 7;
    }
    (x, i - off)
}

/// Expand a sequence of BPE symbols back to the original ASCII name. Each symbol
/// is either a literal (id < alphabet size) or a token that expands to a pair of
/// sub-symbols; tokens are expanded left-first with an explicit stack.
fn expand(enc: &[u8]) -> heapless::String<96> {
    let alpha = OUI_ALPHABET.len();
    let mut out: heapless::String<96> = heapless::String::new();
    let mut stack = [0u8; 128];
    for &sym in enc {
        let mut sp = 0usize;
        stack[sp] = sym;
        sp += 1;
        while sp > 0 {
            sp -= 1;
            let s = stack[sp] as usize;
            if s < alpha {
                let _ = out.push(OUI_ALPHABET[s] as char);
            } else {
                let (l, r) = OUI_DICT[s - alpha];
                // Push right then left so the left sub-symbol expands first.
                if sp < stack.len() {
                    stack[sp] = r;
                    sp += 1;
                }
                if sp < stack.len() {
                    stack[sp] = l;
                    sp += 1;
                }
            }
        }
    }
    out
}
