//! BLE advertising decoders.
//!
//! `log_ad_structures` walks the AD-structure list of a legacy advertising PDU
//! and `decode_ext_adv` handles the BLE-5 extended-advertising header; both emit
//! one readable log line per field and fall back to a hex dump for anything not
//! recognised. Vendor- and service-specific deep decoders live in the submodules
//! below and are reached through the `decode_mfg` / `decode_service_data`
//! dispatchers. Only plaintext, structured fields are decoded; identity fields
//! that vendors encrypt/hash/rotate for privacy are labelled but left as hex.

pub mod asset;
/// Advertising-payload deep decoders, dispatched by Company ID / service UUID.
mod advert;
/// Link-layer and L2CAP-borne protocol decoders for connected links.
pub mod protocol;

/// Fixed-capacity log line. Decoders format into this and hand it to `emit`.
pub type LogStr = crate::LogLine;

/// Queue a finished log line for the USB serial task. Never blocks; the line is
/// dropped if the channel is full (host not draining). Long decoded lines can
/// fill the buffer and lose their "\r\n"; `terminate_line` repairs that so lines
/// never run together.
pub fn emit(mut s: LogStr) {
    crate::terminate_line(&mut s);
    // Route to the active render sink if one is set (inside `write_text_to`),
    // else straight to the LOG channel as before. Reading the raw pointer is sound
    // for the same reason `LOG_STAMP` is: decode is synchronous (no `.await`
    // between a `SinkScope` being set and dropped) on the cooperative executor.
    match unsafe { *CUR_SINK.0.get() } {
        Some(vt) => (vt.line)(vt.data, &s),
        None => crate::log_send(s),
    }
}

// Active render sink as a thin (data pointer, line function) pair — a hand-rolled
// one-method vtable, so no `dyn` object and no fat-pointer/lifetime transmute. The
// raw `data` pointer carries no lifetime; it is valid only for the synchronous
// span of a `SinkScope`.
#[derive(Clone, Copy)]
struct SinkRef {
    data: core::ptr::NonNull<()>,
    line: fn(core::ptr::NonNull<()>, &str),
}
struct CurSink(core::cell::UnsafeCell<Option<SinkRef>>);
unsafe impl Sync for CurSink {}
static CUR_SINK: CurSink = CurSink(core::cell::UnsafeCell::new(None));

/// RAII guard that points [`emit`] at `sink` for the current decode, restoring
/// the previous sink (usually none) on drop. Held across a single, `.await`-free
/// decode of one packet — see [`crate::mode::ble_sniff::Decoded::write_text_to`].
pub struct SinkScope(Option<SinkRef>);

impl SinkScope {
    pub fn new<S: crate::Sink>(sink: &mut S) -> Self {
        fn call<S: crate::Sink>(p: core::ptr::NonNull<()>, s: &str) {
            // Sound: `p` came from a live `&mut S` and is only called within the
            // scope that stored it (decode is synchronous, no `.await` between).
            unsafe { p.cast::<S>().as_mut().line(s) }
        }
        let vt = SinkRef {
            data: core::ptr::NonNull::from(sink).cast::<()>(),
            line: call::<S>,
        };
        let prev = unsafe { (*CUR_SINK.0.get()).replace(vt) };
        SinkScope(prev)
    }
}

impl Drop for SinkScope {
    fn drop(&mut self) {
        unsafe { *CUR_SINK.0.get() = self.0 }
    }
}

// Small tables that stay baked into internal flash as sorted `&[(u16, &str)]`
// literals, all generated by build.rs from the SIG assigned-numbers YAML in
// `assets/`: appearance values (needed even unprovisioned), the AD type names
// (consulted for every AD structure of every packet), and the URI schemes. The
// Company-ID, UUID-name, and OUI tables live in external QSPI flash — see
// `asset`. Refresh the sources with `scripts/refresh_data.py`.
include!(concat!(env!("OUT_DIR"), "/appearance_names.rs")); // APPEARANCE_VALUES
include!(concat!(env!("OUT_DIR"), "/ad_type_names.rs")); // AD_TYPE_NAMES
include!(concat!(env!("OUT_DIR"), "/uri_schemes.rs")); // URI_SCHEMES

/// Binary-search a sorted `(u16, &str)` SIG table.
fn lookup(table: &'static [(u16, &'static str)], id: u16) -> Option<&'static str> {
    table.binary_search_by_key(&id, |&(k, _)| k).ok().map(|i| table[i].1)
}

/// Look up a Bluetooth SIG Company Identifier (the manufacturer-data prefix)
/// in the full SIG registry. `None` for ids not present or unprovisioned.
///
/// Two ids are intercepted before the registry, because the registry answer for
/// them is worse than no answer:
///
/// * `0x0000` really is Ericsson Technology Licensing — the very first entry the
///   SIG ever assigned — but a manufacturer-data field opening `00 00` is nearly
///   always an uninitialised or padded id, not an Ericsson product. The
///   2026-08-02 capture had no plausible Ericsson device in it.
/// * `0xFFFF` is reserved by the SIG for internal/testing use and is what an
///   integrator ships when they never applied for an id (306 devices in that
///   same capture). Naming it as such is the useful decode.
pub fn company_name(id: u16) -> Option<&'static str> {
    match id {
        0x0000 => Some("unset/invalid company ID"),
        0xFFFF => Some("no assigned company ID (SIG reserved 0xFFFF)"),
        _ => asset::company_name(id),
    }
}

/// Look up the IEEE vendor for a public MAC: `prefix` is the 24-bit OUI (the top
/// three octets) and `ext12` the 12 bits below it, which name the assignee when
/// IEEE has subdivided that OUI. Returns the org name in a stack buffer, `None`
/// if unassigned or unprovisioned.
pub fn oui_vendor(prefix: u32, ext12: Option<u16>) -> Option<heapless::String<96>> {
    // 00:00:00 is assigned to Xerox and FF:FF:FF is the broadcast prefix; an
    // address starting with either is an unset field, not a device from those
    // vendors. Answering the registry question honestly here would attach a
    // confident, wrong manufacturer to every zeroed address in the log.
    if prefix == 0x00_0000 || prefix == 0xFF_FFFF {
        return None;
    }
    asset::oui_vendor(prefix, ext12)
}

/// Print a 6-byte MAC-48 held in display (MSB-first) order as `AA:BB:…:FF`.
/// Vendor payloads that embed an address mostly carry it this way round, unlike
/// the packet header's AdvA, which goes out LSB-first.
pub fn write_mac_be(s: &mut LogStr, m: &[u8]) {
    use core::fmt::Write;
    for (i, b) in m.iter().enumerate() {
        if i > 0 { let _ = write!(s, ":"); }
        let _ = write!(s, "{:02X}", b);
    }
}

/// Emit an `    oui: <org>` line naming the IEEE holder of `m`'s top three
/// octets (display order). An address embedded in a payload is a stable
/// identifier even when the advertising address rotates, so its assignee is
/// worth resolving. Emits nothing for a locally administered address (bit 1 of
/// the first octet), which carries no IEEE assignment, or for an unassigned OUI.
///
/// A payload carrying at least five octets also resolves subdivided blocks,
/// where the 24-bit OUI alone names only the registrar.
pub fn emit_oui_vendor(m: &[u8]) {
    use core::fmt::Write;
    if m.len() < 3 || m[0] & 0x02 != 0 { return; }
    let prefix = (m[0] as u32) << 16 | (m[1] as u32) << 8 | m[2] as u32;
    let ext12 = (m.len() >= 5).then(|| (m[3] as u16) << 4 | (m[4] >> 4) as u16);
    if let Some(v) = oui_vendor(prefix, ext12) {
        let mut s: LogStr = LogStr::new();
        let _ = write!(s, "    oui: {}", v);
        emit(s);
    }
}

/// Look up a 16-bit service/member/SDO UUID name. `None` if unassigned or
/// unprovisioned.
pub fn uuid_name(id: u16) -> Option<&'static str> {
    asset::uuid_name(id)
}

/// Append " (Name)" for a known 16-bit UUID, nothing otherwise.
fn write_uuid_name(s: &mut LogStr, id: u16) {
    use core::fmt::Write;
    if let Some(n) = uuid_name(id) {
        let _ = write!(s, "({}) ", n);
    }
}

/// Human-readable name for a Bluetooth SIG AD (GAP data) type.
///
/// The match holds a short label for every type the SIG has assigned, chosen to
/// keep the log line narrow ("UUID16-more" for "Incomplete List of 16-bit
/// Service or Service Class UUIDs"). `AD_TYPE_NAMES`, generated from the SIG's
/// `core/ad_types.yaml`, backs it up: a type added to the registry after this
/// match was written still gets its official name rather than "Unknown", so
/// refreshing the YAML is enough to stay current.
fn ad_type_name(t: u8) -> &'static str {
    let short = match t {
        0x01 => "Flags",
        0x02 => "UUID16-more",
        0x03 => "UUID16",
        0x04 => "UUID32-more",
        0x05 => "UUID32",
        0x06 => "UUID128-more",
        0x07 => "UUID128",
        0x08 => "ShortName",
        0x09 => "Name",
        0x0A => "TxPower",
        0x0D => "ClassOfDevice",
        0x0E => "PairingHashC192",
        0x0F => "PairingRandomizerR192",
        0x10 => "DeviceID/SM-TK",
        0x11 => "SM-OOB-Flags",
        0x12 => "ConnIntervalRange",
        0x14 => "Solicit-UUID16",
        0x15 => "Solicit-UUID128",
        0x16 => "ServiceData16",
        0x17 => "PublicTargetAddr",
        0x18 => "RandomTargetAddr",
        0x19 => "Appearance",
        0x1A => "AdvInterval",
        0x1B => "LEDeviceAddr",
        0x1C => "LERole",
        0x1D => "PairingHashC256",
        0x1E => "PairingRandomizerR256",
        0x1F => "Solicit-UUID32",
        0x20 => "ServiceData32",
        0x21 => "ServiceData128",
        0x22 => "LESC-Confirm",
        0x23 => "LESC-Random",
        0x24 => "URI",
        0x25 => "IndoorPositioning",
        0x26 => "TransportDiscovery",
        0x27 => "LEFeatures",
        0x28 => "ChannelMapUpdate",
        0x29 => "PB-ADV",
        0x2A => "MeshMessage",
        0x2B => "MeshBeacon",
        0x2C => "BIGInfo",
        0x2D => "BroadcastCode",
        0x2E => "RSI",
        0x2F => "AdvInterval-long",
        0x30 => "BroadcastName",
        0x31 => "EncryptedAdvData",
        0x32 => "PeriodicAdvResponseTiming",
        0x34 => "ElectronicShelfLabel",
        0x3D => "3DInformation",
        0xFF => "MfgData",
        _    => "",
    };
    if !short.is_empty() {
        return short;
    }
    lookup(AD_TYPE_NAMES, t as u16).unwrap_or("Unknown")
}

/// The URI scheme prefix a URI AD structure (0x24) opens with. The scheme is a
/// SIG code point encoded as one UTF-8 character, so it is read as a character
/// rather than a byte — codes above 0x7F take two bytes on air. Returns the
/// scheme name and the byte length it occupied.
fn uri_scheme(data: &[u8]) -> Option<(&'static str, usize)> {
    let s = core::str::from_utf8(data).ok()?;
    let c = s.chars().next()?;
    let name = lookup(URI_SCHEMES, u16::try_from(c as u32).ok()?)?;
    Some((name, c.len_utf8()))
}

/// LE Role (AD 0x1C) value → the roles the device supports and which it prefers.
fn le_role_name(r: u8) -> &'static str {
    match r {
        0x00 => "peripheral only",
        0x01 => "central only",
        0x02 => "peripheral+central, peripheral preferred",
        0x03 => "peripheral+central, central preferred",
        _    => "rfu",
    }
}

/// GAP appearance value → label. Prefers an exact subcategory match, falling
/// back to the generic category (subcategory 0), then "?".
pub fn appearance_name(a: u16) -> &'static str {
    lookup(APPEARANCE_VALUES, a)
        .or_else(|| lookup(APPEARANCE_VALUES, (a >> 6) << 6))
        .unwrap_or("?")
}

/// Class of Device major device class (bits 12..8 → 5-bit code).
fn cod_major(major: u8) -> &'static str {
    match major {
        0x00 => "Miscellaneous",
        0x01 => "Computer",
        0x02 => "Phone",
        0x03 => "LAN/Network AP",
        0x04 => "Audio/Video",
        0x05 => "Peripheral",
        0x06 => "Imaging",
        0x07 => "Wearable",
        0x08 => "Toy",
        0x09 => "Health",
        0x1F => "Uncategorized",
        _    => "?",
    }
}

/// Append the set major service-class flags (Class of Device bits 23..13).
fn write_cod_services(s: &mut LogStr, cod: u32) {
    use core::fmt::Write;
    const SVC: [(u32, &str); 11] = [
        (13, "LimitedDiscoverable"),
        (14, "LE-Audio"),
        (15, "Reserved"),
        (16, "Positioning"),
        (17, "Networking"),
        (18, "Rendering"),
        (19, "Capturing"),
        (20, "ObjectTransfer"),
        (21, "Audio"),
        (22, "Telephony"),
        (23, "Information"),
    ];
    let mut first = true;
    for (bit, name) in SVC {
        if cod & (1 << bit) != 0 {
            let _ = write!(s, "{}{}", if first { " [" } else { " " }, name);
            first = false;
        }
    }
    if !first { let _ = write!(s, "]"); }
}

/// Append an advertising interval given in 0.625 ms units as milliseconds with
/// two decimal places (`0x00A0` → `100.00ms`).
fn write_interval(s: &mut LogStr, units: u32) {
    use core::fmt::Write;
    let us = units * 625;
    let _ = write!(s, "{}.{:02}ms", us / 1000, (us % 1000) / 10);
}

pub fn write_hex(s: &mut LogStr, data: &[u8]) {
    use core::fmt::Write;
    for b in data {
        let _ = write!(s, "{:02X}", b);
    }
}

/// Emit `data` as a multi-line hexdump (classic `hexdump -C` style): up to 16
/// space-separated bytes per line in two groups of eight, then an ASCII gutter
/// where printable bytes
/// (0x20..=0x7E) render as themselves and everything else as '.'. Each line is
/// prefixed with `p{XX}:r{XX}:` where `p` is the byte offset within the decoded
/// field (`base` + block offset) and `r` is the offset within this hex block.
/// The hex column is padded on a short final row so the ASCII gutter stays
/// aligned. Breaking long blobs across lines keeps every line well under the
/// buffer cap, so no line can overflow and lose its terminator. Emits nothing
/// when `data` is empty.
pub fn hexdump(data: &[u8], base: usize, indent: usize) {
    use core::fmt::Write;
    // Classify every byte for the gutter once, over the whole payload, so a
    // multi-byte UTF-8 character that straddles a 16-byte line boundary renders
    // correctly: its lead byte shows the glyph on one line, and its continuation
    // bytes show `·` (GUT_CONT) on the following line. Classes: GUT_START (first
    // byte of a printable UTF-8 char), GUT_CONT (a following byte of one), or
    // GUT_DOT (a control char or a byte that is not valid UTF-8).
    let mut cls = [GUT_DOT; 256];
    let n = data.len().min(cls.len());
    let mut i = 0;
    while i < n {
        match core::str::from_utf8(&data[i..n]) {
            Ok(s) => {
                classify_gutter(s, i, &mut cls);
                break;
            }
            Err(e) => {
                let vu = e.valid_up_to();
                if vu > 0
                    && let Ok(s) = core::str::from_utf8(&data[i..i + vu])
                {
                    classify_gutter(s, i, &mut cls);
                }
                match e.error_len() {
                    Some(l) => i += vu + l,
                    None => break,
                }
            }
        }
    }

    for (row, chunk) in data.chunks(16).enumerate() {
        let rel = row * 16;
        let mut s: LogStr = LogStr::new();
        for _ in 0..indent {
            let _ = s.push(' ');
        }
        let _ = write!(s, "p{:02X}:r{:02X}: ", base + rel, rel);
        for (k, b) in chunk.iter().enumerate() {
            // Bytes run together within each half; a single space at the halfway
            // mark, as `hexdump -C` does, gives the eye a fixed landmark to count
            // from so picking byte 11 out of a row is two short counts rather than
            // one long one.
            if k == 8 {
                let _ = s.push(' ');
            }
            let _ = write!(s, "{:02X}", b);
        }
        // Pad the hex column (2 chars/byte, plus the halfway space if this row
        // stopped before it) so the ASCII gutter aligns on a short final row.
        for _ in 0..(16 - chunk.len()) {
            let _ = s.push_str("  ");
        }
        if chunk.len() <= 8 {
            let _ = s.push(' ');
        }
        let _ = s.push_str("  ");
        for (k, &b) in chunk.iter().enumerate() {
            let pos = rel + k;
            let g = if pos < n { cls[pos] } else { GUT_DOT };
            let c = match g {
                GUT_START => {
                    // Re-decode the one char that starts at this byte.
                    let end = (pos + utf8_len(b)).min(n);
                    core::str::from_utf8(&data[pos..end])
                        .ok()
                        .and_then(|t| t.chars().next())
                        .unwrap_or('.')
                }
                GUT_CONT => '·',
                _ => '.',
            };
            let _ = s.push(c);
        }
        emit(s);
    }
}

// Byte classes for the hexdump gutter.
const GUT_DOT: u8 = 0;
const GUT_CONT: u8 = 1;
const GUT_START: u8 = 2;

/// Mark the byte classes for the printable characters in `s` (a valid-UTF-8 run
/// that begins at byte `seg_base` of the payload) into `cls`. Control characters
/// are left as `GUT_DOT`.
fn classify_gutter(s: &str, seg_base: usize, cls: &mut [u8]) {
    for (off, c) in s.char_indices() {
        let g = seg_base + off;
        if g >= cls.len() {
            break;
        }
        if c.is_control() {
            continue; // leave as GUT_DOT
        }
        cls[g] = GUT_START;
        for j in 1..c.len_utf8() {
            if g + j < cls.len() {
                cls[g + j] = GUT_CONT;
            }
        }
    }
}

/// Number of bytes in the UTF-8 sequence whose lead byte is `b` (1 for ASCII).
fn utf8_len(b: u8) -> usize {
    if b < 0x80 {
        1
    } else if b >= 0xF0 {
        4
    } else if b >= 0xE0 {
        3
    } else {
        2
    }
}

/// Whether the advertiser's own 6-byte address appears anywhere in `data`, in
/// either byte order. `adva` is the on-air (little-endian) address; payloads
/// carry it both that way round and in display order.
fn contains_addr(data: &[u8], adva: &[u8; 6]) -> bool {
    let mut rev = *adva;
    rev.reverse();
    data.windows(6).any(|w| w == adva.as_slice() || w == rev.as_slice())
}

/// The GATT role a SIG-assigned 16-bit service UUID implies, for frames whose
/// only interpretable content is the service list. Grouped rather than named
/// one-for-one: the per-UUID name is already on the AD line, so what this adds
/// is what the device *is*.
fn service_role(u: u16) -> Option<&'static str> {
    Some(match u {
        0x1812 => "HID input",
        0x180F => "battery",
        0x180A => "device-info",
        0x1802..=0x1804 => "proximity/alert",
        0x1805 | 0x1806 => "time sync",
        0x1808 | 0x1809 | 0x180D | 0x1810 | 0x181B | 0x181D | 0x1822 | 0x1823 => "health sensor",
        0x1814 | 0x1816 | 0x1818 | 0x1826 => "fitness sensor",
        0x1819 | 0x1821 | 0x1825 => "location/navigation",
        0x181A => "environmental sensor",
        0x1811 => "alert notification",
        0x1813 => "scan parameters",
        0x1815 => "automation I/O",
        0x1827 => "mesh provisioning (unprovisioned)",
        0x1828 => "mesh proxy",
        0x1843..=0x1856 => "LE Audio",
        0xFE59 => "Nordic DFU (firmware update)",
        0xFD6F => "exposure notification",
        0xFFF0 => "PKOC credential",
        _ => return None,
    })
}

/// Record `u`'s role once, keeping the first-seen order.
fn push_role(roles: &mut heapless::Vec<&'static str, 8>, u: u16) {
    if let Some(r) = service_role(u)
        && !roles.contains(&r)
    {
        let _ = roles.push(r);
    }
}

/// Emit a container header line alone (`  MfgData (0xFF):`), for AD types whose
/// contents break onto indented child lines below it.
fn emit_ad_header(ad_type: u8) {
    use core::fmt::Write;
    let mut h: LogStr = LogStr::new();
    let _ = write!(h, "  {} (0x{:02X}):", ad_type_name(ad_type), ad_type);
    emit(h);
}

/// Walk every AD structure in `adv_data` and log one decoded line each.
///
/// AdvData is a sequence of AD structures, each `[len][type][data (len-1 bytes)]`.
/// Returns how many bytes of `adv_data` the walk accounted for. The caller
/// hex-dumps the remainder and nothing else — see [`crate::mode::ble_sniff`] — so a
/// packet whose structures all decode gets no dump, and one with a few bytes of
/// tail junk gets one short line instead of the whole payload again.
///
/// A trailing run of zeros counts as accounted for: a zero length byte is the
/// spec's end-of-data marker and the padding after it carries nothing. Anything
/// else the walk stops on — a length running past the buffer, a stray byte too
/// short to be a structure — does not, because that is exactly the case where
/// the raw bytes are the only record of what arrived.
/// `verified` is the frame's CRC status. On an unverified (CRC-salvaged) frame
/// the AD-structure boundaries still walk clean — that is the salvage gate — but
/// the field *contents* are unproven, so the deeper vendor sub-decoders (Apple
/// Continuity, mesh bearers, service-data decoders) are skipped and their bodies
/// dumped raw. Running them on corrupt bytes invents phantom sub-messages.
pub fn log_ad_structures(adv_data: &[u8], adva: Option<[u8; 6]>, verified: bool) -> usize {
    use core::fmt::Write;

    // Bytes consumed by complete structures; the walk's stopping point.
    let mut consumed = 0usize;

    // Synthesised into one `profile:` line after the walk. A frame whose whole
    // payload is a service-UUID list gets no vendor decode, so this is the only
    // thing that says a bare 0x1812 advertiser is a HID peripheral.
    let mut roles: heapless::Vec<&'static str, 8> = heapless::Vec::new();
    let mut appearance: Option<u16> = None;

    let mut i = 0;
    while i + 1 < adv_data.len() {
        let field_len = adv_data[i] as usize;
        if field_len == 0 {
            // End-of-data marker. The rest is padding when it is all zeros, and
            // padding is accounted for; a non-zero tail is not.
            if adv_data[i..].iter().all(|&b| b == 0) {
                consumed = adv_data.len();
            }
            break;
        }
        let data_end = i + 1 + field_len; // length byte covers type + data
        if data_end > adv_data.len() { break; } // truncated structure
        let ad_type = adv_data[i + 1];
        let data = &adv_data[i + 2..data_end];

        // Some cheap beacons stuff their own 6-byte BD_ADDR into the manufacturer
        // field, so the "Company ID" is just the low two bytes of the MAC. Detect
        // this so we flag it instead of reporting a bogus vendor.
        let mfg_is_own_addr =
            ad_type == 0xFF && matches!(adva, Some(a) if data == a.as_slice());

        // A whole family of cheap IoT beacons (e-bikes/scooters, GPS trackers)
        // put two octets of their *own* address into the 2-byte Company-ID slot
        // — an unregistered ID that happens to equal part of the MAC (e.g. addr
        // A1:4A:… advertises Company-ID 0x4AA1). `adva` is the on-air
        // little-endian address, so a[5],a[4] are the leading display octets and
        // a[0],a[1] the trailing pair; both ends turn up in captures. This is a
        // fingerprint/privacy leak and protocol misuse, not a real vendor.
        let mfg_cid_is_own_prefix = ad_type == 0xFF
            && data.len() >= 2
            && !mfg_is_own_addr
            && matches!(adva, Some(a) if (data[0] == a[5] && data[1] == a[4])
                                      || (data[0] == a[0] && data[1] == a[1]));

        // Others carry the whole address somewhere inside the body instead of at
        // its start, so the Company ID looks legitimate while the frame still
        // republishes the identity the rotating address is supposed to hide.
        let mfg_body_has_own_addr = ad_type == 0xFF
            && !mfg_is_own_addr
            && matches!(adva, Some(a) if contains_addr(data, &a));

        let mut s: LogStr = LogStr::new();
        let _ = write!(s, "  {} (0x{:02X}): ", ad_type_name(ad_type), ad_type);

        // Raw byte blobs are not printed inline (they overflow long lines);
        // instead the arm records `(bytes, field-offset)` here and we hexdump
        // them on their own lines after the header line is emitted.
        let mut tail: Option<(&[u8], usize)> = None;

        // Container/list arms (MfgData, ServiceData, multi-entry UUID lists) emit
        // their own header + indented children and set this, so the generic
        // single-line emit + tail dump below is skipped for them.
        let mut handled = false;

        match ad_type {
            0x01 => {
                // Flags bitfield.
                let f = data.first().copied().unwrap_or(0);
                let _ = write!(s, "0x{:02X}", f);
                if f & 0x01 != 0 { let _ = write!(s, " LE-Limited"); }
                if f & 0x02 != 0 { let _ = write!(s, " LE-General"); }
                if f & 0x04 != 0 { let _ = write!(s, " NoBREDR"); }
                if f & 0x08 != 0 { let _ = write!(s, " LE+BREDR-Ctrl"); }
                // Bit 4 named the host half of the same simultaneous-LE/BR-EDR
                // capability until the SIG withdrew it; CSS Part A Table 1.4
                // now reads "Previously Used". Stacks predating the withdrawal
                // still set it, so it is worth showing under a name that does
                // not claim a capability the spec no longer defines.
                if f & 0x10 != 0 { let _ = write!(s, " PreviouslyUsed"); }
            }
            0x08 | 0x09 => {
                // Local name (UTF-8, else hex).
                match core::str::from_utf8(data) {
                    Ok(n)  => { let _ = write!(s, "{}", n); }
                    Err(_) => tail = Some((data, 0)),
                }
            }
            0x0A => {
                // TX power, signed dBm.
                let p = data.first().copied().unwrap_or(0) as i8;
                let _ = write!(s, "{} dBm", p);
            }
            0x19 => {
                // Appearance, u16 little-endian.
                if data.len() >= 2 {
                    let a = u16::from_le_bytes([data[0], data[1]]);
                    appearance = Some(a);
                    let _ = write!(s, "0x{:04X} ({})", a, appearance_name(a));
                } else {
                    tail = Some((data, 0));
                }
            }
            0x02 | 0x03 | 0x14 => {
                // 16-bit UUID list — annotate assigned SIG UUIDs with their name.
                // Two or more break into a dashed child list; a single UUID stays
                // inline on the header line.
                if data.len() / 2 >= 2 {
                    emit_ad_header(ad_type);
                    for pair in data.chunks(2) {
                        if pair.len() == 2 {
                            let u = u16::from_le_bytes([pair[0], pair[1]]);
                            push_role(&mut roles, u);
                            let mut c: LogStr = LogStr::new();
                            let _ = write!(c, "    - {:04X} ", u);
                            write_uuid_name(&mut c, u);
                            emit(c);
                        }
                    }
                    handled = true;
                } else {
                    for pair in data.chunks(2) {
                        if pair.len() == 2 {
                            let u = u16::from_le_bytes([pair[0], pair[1]]);
                            push_role(&mut roles, u);
                            let _ = write!(s, "{:04X} ", u);
                            write_uuid_name(&mut s, u);
                        }
                    }
                }
            }
            0x04 | 0x05 | 0x1F => {
                // 32-bit UUID list.
                if data.len() / 4 >= 2 {
                    emit_ad_header(ad_type);
                    for q in data.chunks(4) {
                        if q.len() == 4 {
                            let mut c: LogStr = LogStr::new();
                            let _ = write!(c, "    - {:08X}",
                                u32::from_le_bytes([q[0], q[1], q[2], q[3]]));
                            emit(c);
                        }
                    }
                    handled = true;
                } else {
                    for q in data.chunks(4) {
                        if q.len() == 4 {
                            let _ = write!(s, "{:08X} ", u32::from_le_bytes([q[0], q[1], q[2], q[3]]));
                        }
                    }
                }
            }
            0x06 | 0x07 | 0x15 => {
                // 128-bit UUID list — transmitted LE, print MSB-first.
                if data.len() / 16 >= 2 {
                    emit_ad_header(ad_type);
                    for chunk in data.chunks(16) {
                        if chunk.len() == 16 {
                            let mut c: LogStr = LogStr::new();
                            let _ = write!(c, "    - ");
                            for b in chunk.iter().rev() {
                                let _ = write!(c, "{:02X}", b);
                            }
                            emit(c);
                        }
                    }
                    handled = true;
                } else {
                    for chunk in data.chunks(16) {
                        for b in chunk.iter().rev() {
                            let _ = write!(s, "{:02X}", b);
                        }
                        let _ = write!(s, " ");
                    }
                }
            }
            0x16 if data.len() >= 2 => {
                // Service data, 16-bit UUID prefix — a container: UUID on its own
                // child line, then the service-specific decode (or a raw body dump
                // if the UUID is unknown).
                let u = u16::from_le_bytes([data[0], data[1]]);
                push_role(&mut roles, u);
                emit_ad_header(ad_type);
                let mut c: LogStr = LogStr::new();
                let _ = write!(c, "    uuid={:04X} ", u);
                write_uuid_name(&mut c, u);
                let _ = write!(c, "len={}", data.len() - 2);
                emit(c);
                if verified {
                    advert::decode_service_data(data, adva);
                } else {
                    hexdump(&data[2..], 2, 6);
                }
                handled = true;
            }
            0x0D => {
                // Class of Device (3 bytes, LE): service-class bits (23..13),
                // major device class (12..8), minor device class (7..2).
                if data.len() >= 3 {
                    let cod = u32::from_le_bytes([data[0], data[1], data[2], 0]);
                    let _ = write!(s, "0x{:06X} {}", cod, cod_major(((cod >> 8) & 0x1F) as u8));
                    write_cod_services(&mut s, cod);
                } else {
                    tail = Some((data, 0));
                }
            }
            0x24 => {
                // URI: the scheme goes out as a SIG code point rather than
                // spelled out, so it is expanded here and the remainder of the
                // field is the rest of the URI as UTF-8.
                match (uri_scheme(data), core::str::from_utf8(data)) {
                    (Some((scheme, n)), Ok(u)) => { let _ = write!(s, "{}{}", scheme, &u[n..]); }
                    (None, Ok(u)) => { let _ = write!(s, "{}", u); }
                    _ => tail = Some((data, 0)),
                }
            }
            0x20 if data.len() >= 4 => {
                // Service data, 32-bit UUID prefix — a container: UUID on its own
                // child line, then the raw body dump.
                emit_ad_header(ad_type);
                let mut c: LogStr = LogStr::new();
                let _ = write!(c, "    uuid={:08X} len={}",
                    u32::from_le_bytes([data[0], data[1], data[2], data[3]]),
                    data.len() - 4);
                emit(c);
                hexdump(&data[4..], 4, 6);
                handled = true;
            }
            0x21 if data.len() >= 16 => {
                // Service data, 128-bit UUID prefix — transmitted LE, print
                // MSB-first so it reads as the canonical UUID. A container: UUID on
                // its own child line, then the raw body dump.
                emit_ad_header(ad_type);
                let mut c: LogStr = LogStr::new();
                let _ = write!(c, "    uuid=");
                for b in data[..16].iter().rev() {
                    let _ = write!(c, "{:02X}", b);
                }
                let _ = write!(c, " len={}", data.len() - 16);
                emit(c);
                hexdump(&data[16..], 16, 6);
                handled = true;
            }
            0x1B => {
                // LE Bluetooth Device Address: the identity address, 6 bytes LE
                // plus a type octet. Published under a rotating RPA it defeats
                // the rotation, so it is worth naming explicitly.
                if data.len() >= 7 {
                    let a = &data[..6];
                    let _ = write!(s, "{:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X} {}",
                        a[5], a[4], a[3], a[2], a[1], a[0],
                        if data[6] & 1 == 0 { "public" } else { "random" });
                } else {
                    tail = Some((data, 0));
                }
            }
            0x17 | 0x18 => {
                // Target address list — one or more 6-byte addresses, each LE.
                // Two or more break into a dashed child list; a single address
                // stays inline on the header line.
                if data.len() / 6 >= 2 {
                    emit_ad_header(ad_type);
                    for a in data.chunks(6) {
                        if a.len() == 6 {
                            let mut c: LogStr = LogStr::new();
                            let _ = write!(c, "    - {:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}",
                                a[5], a[4], a[3], a[2], a[1], a[0]);
                            emit(c);
                        }
                    }
                    handled = true;
                } else {
                    for a in data.chunks(6) {
                        if a.len() == 6 {
                            let _ = write!(s, "{:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X} ",
                                a[5], a[4], a[3], a[2], a[1], a[0]);
                        }
                    }
                }
            }
            0x1C => {
                // LE Role, one octet.
                if let Some(&r) = data.first() {
                    let _ = write!(s, "0x{:02X} ({})", r, le_role_name(r));
                } else {
                    tail = Some((data, 0));
                }
            }
            0x1A => {
                // Advertising Interval, u16 LE in 0.625 ms units.
                if data.len() >= 2 {
                    write_interval(&mut s, u16::from_le_bytes([data[0], data[1]]) as u32);
                } else {
                    tail = Some((data, 0));
                }
            }
            0x2F => {
                // Advertising Interval - long: 3 or 4 octets LE, 0.625 ms units.
                match data.len() {
                    3 => write_interval(&mut s, u32::from_le_bytes([data[0], data[1], data[2], 0])),
                    4 => write_interval(&mut s, u32::from_le_bytes([data[0], data[1], data[2], data[3]])),
                    _ => tail = Some((data, 0)),
                }
            }
            0x2E => {
                // Resolvable Set Identifier (CSIP): SIRK hash (3 octets) then
                // the random it was derived from (3 octets), both LE. Only a set
                // member holding the SIRK can resolve it, but the pair is stable
                // for as long as `prand` is reused.
                if data.len() >= 6 {
                    let _ = write!(s, "hash={:02X}{:02X}{:02X} prand={:02X}{:02X}{:02X}",
                        data[2], data[1], data[0], data[5], data[4], data[3]);
                    // Set correlation (#9): with a matching SIRK compiled in, tag
                    // the coordinated-set this member belongs to. Off unless built
                    // with `resolve-identities`.
                    #[cfg(feature = "resolve-identities")]
                    {
                        let prand = [data[5], data[4], data[3]];
                        let hash = [data[2], data[1], data[0]];
                        for (sirk, label) in crate::keys::SIRKS {
                            if crate::hal::crypto::ah(sirk, &prand) == hash {
                                let _ = write!(s, " set={}", label);
                                break;
                            }
                        }
                    }
                } else {
                    tail = Some((data, 0));
                }
            }
            0x30 => {
                // Broadcast_Name (LE Audio), UTF-8.
                match core::str::from_utf8(data) {
                    Ok(n)  => { let _ = write!(s, "{}", n); }
                    Err(_) => tail = Some((data, 0)),
                }
            }
            0x28 => {
                // Channel Map Update Indication: 5-octet channel map then the
                // connection event instant it takes effect at (u16 LE).
                if data.len() >= 7 {
                    let used: u32 = data[..5].iter().map(|b| b.count_ones()).sum();
                    let _ = write!(s, "chmap={:02X}{:02X}{:02X}{:02X}{:02X} ({} ch) instant={}",
                        data[0], data[1], data[2], data[3], data[4], used,
                        u16::from_le_bytes([data[5], data[6]]));
                } else {
                    tail = Some((data, 0));
                }
            }
            0x27 => {
                // LE Supported Features, a little-endian bitfield of whatever
                // length the advertiser chose to send.
                let _ = write!(s, "0x");
                for b in data.iter().rev() {
                    let _ = write!(s, "{:02X}", b);
                }
            }
            0x2C => {
                // BIGInfo (rides in periodic ACAD): the Broadcast Isochronous
                // Group parameters a receiver needs to sync to an Auracast /
                // LE-Audio broadcast stream.
                biginfo_summary(&mut s, data);
            }
            0x31 => {
                // Encrypted Advertising Data (Core v5.4 Vol 3 Part C §11):
                // 5-byte Randomizer, ciphertext, 4-byte MIC. Undecryptable
                // without the session key, but the layout is worth surfacing.
                if data.len() >= 9 {
                    let mic = &data[data.len() - 4..];
                    let _ = write!(s,
                        "randomizer={:02X}{:02X}{:02X}{:02X}{:02X} payload={}B mic={:02X}{:02X}{:02X}{:02X}",
                        data[0], data[1], data[2], data[3], data[4], data.len() - 9,
                        mic[0], mic[1], mic[2], mic[3]);
                } else {
                    tail = Some((data, 0));
                }
            }
            0xFF if mfg_is_own_addr => {
                // The field equals the advertiser's own address — not a vendor.
                let _ = write!(s, "own-address (not a vendor)");
                tail = Some((data, 0));
            }
            // Manufacturer-specific: first 2 bytes = Company ID (LE). Too short
            // for one and it falls through to the catch-all, which dumps the
            // bytes as they came. A container: the company on its own child line,
            // then the vendor deep-decode (or a raw body dump if unknown).
            0xFF if data.len() >= 2 => {
                let cid = u16::from_le_bytes([data[0], data[1]]);
                emit_ad_header(ad_type);
                let mut c: LogStr = LogStr::new();
                let _ = write!(c, "    ");
                if mfg_cid_is_own_prefix {
                    // Company-ID == own MAC prefix: not a vendor, a privacy leak.
                    let _ = write!(c, "0x{:04X} (own-MAC-prefix, unregistered) ", cid);
                } else {
                    match company_name(cid) {
                        Some(n) => { let _ = write!(c, "{} (0x{:04X}) ", n, cid); }
                        // 0xFFFF is the SIG "no company / internal use" value.
                        None if cid == 0xFFFF => {
                            let _ = write!(c, "0xFFFF (reserved/test — not a real company) ");
                        }
                        None => {
                            let _ = write!(c, "0x{:04X} (unregistered", cid);
                            // Some makers type two characters into the
                            // Company-ID slot as a brand tag rather than
                            // registering: 0x5944 is the ASCII "DY". The
                            // bytes go out little-endian, so data[0] is the
                            // first character.
                            if data[0].is_ascii_graphic() && data[1].is_ascii_graphic() {
                                let _ = write!(c, ", ascii \"{}{}\"",
                                    data[0] as char, data[1] as char);
                            }
                            let _ = write!(c, ") ");
                        }
                    }
                }
                let _ = write!(c, "len={}", data.len() - 2);
                emit(c);
                if mfg_body_has_own_addr {
                    let mut n: LogStr = LogStr::new();
                    let _ = write!(n, "    own address embedded in manufacturer data (identity leak)");
                    emit(n);
                }
                if mfg_cid_is_own_prefix || !verified {
                    // Not a vendor, or a CRC-salvaged frame whose body is unproven —
                    // show the raw body under the container instead of running a
                    // vendor decoder that would invent phantom sub-messages.
                    hexdump(&data[2..], 2, 6);
                } else {
                    advert::decode_mfg(data);
                }
                handled = true;
            }
            _ => {
                tail = Some((data, 0));
            }
        }

        // Inline (non-container) types: one header line, then their unparsed tail
        // one level deeper. Container/list arms already emitted everything above.
        if !handled {
            if let Some((t, _)) = tail
                && !t.is_empty()
            {
                let _ = write!(s, " len={}", t.len());
            }
            emit(s);
            if let Some((t, b)) = tail {
                hexdump(t, b, 4);
            }

            // Mesh advertising bearers carry their own PDU formats, decoded below
            // the header line — but only on a CRC-verified frame; on salvage the
            // tail hexdump above is all that can be trusted.
            if verified {
                match ad_type {
                    0x29 => advert::mesh::decode_pb_adv(data),
                    0x2A => advert::mesh::decode_message(data),
                    0x2B => advert::mesh::decode_beacon(data),
                    _ => {}
                }
            }
        }
        i = data_end;
        consumed = i;
    }

    // Appearance alone repeats the 0x19 line, so the summary needs at least one
    // service role to be worth a line of its own.
    if !roles.is_empty() {
        let mut s: LogStr = LogStr::new();
        let _ = write!(s, "  profile:");
        for (k, r) in roles.iter().enumerate() {
            let _ = write!(s, "{} {}", if k == 0 { "" } else { "," }, r);
        }
        if let Some(a) = appearance {
            let _ = write!(s, " · appearance {} (0x{:04X})", appearance_name(a), a);
        }
        emit(s);
    }

    consumed
}

/// Read `n` bits (LSB-first) starting at bit offset `bo` from a little-endian
/// bitstream. Used to unpack the tightly-packed BIGInfo field.
fn bits_le(d: &[u8], bo: usize, n: usize) -> u64 {
    let mut v = 0u64;
    for i in 0..n {
        let bit = bo + i;
        if d.get(bit / 8).is_some_and(|b| (b >> (bit % 8)) & 1 != 0) {
            v |= 1 << i;
        }
    }
    v
}

/// Summarise a BIGInfo (AD 0x2C) field — the LL Broadcast Isochronous Group
/// parameters (Core v5.4 Vol 6 Part B §2.3.4.9) that a receiver needs to sync to
/// an LE-Audio / Auracast broadcast. Unencrypted BIGInfo is 33 bytes, encrypted
/// is 57 (the trailing GIV/GSKD present only when encrypted).
fn biginfo_summary(s: &mut LogStr, d: &[u8]) {
    use core::fmt::Write;
    if d.len() < 33 {
        let _ = write!(s, "truncated ({}B)", d.len());
        return;
    }
    let num_bis = bits_le(d, 27, 5);
    let iso_x100 = bits_le(d, 15, 12) * 125; // Iso_Interval, 1.25 ms units → ms×100
    let sdu_interval = bits_le(d, 136, 20); // µs
    let max_pdu = bits_le(d, 88, 8);
    let max_sdu = bits_le(d, 156, 12);
    let seed_aa = bits_le(d, 104, 32) as u32;
    let phy = bits_le(d, 221, 3);
    let framing = bits_le(d, 263, 1);
    let phy_s = match phy {
        1 => "1M",
        2 => "2M",
        4 => "Coded",
        _ => "?",
    };
    let _ = write!(
        s,
        "bis={} iso={}.{:02}ms sdu={}us max_pdu={} max_sdu={} phy={} {} seed_aa=0x{:08X} enc={}",
        num_bis,
        iso_x100 / 100,
        iso_x100 % 100,
        sdu_interval,
        max_pdu,
        max_sdu,
        phy_s,
        if framing == 1 { "framed" } else { "unframed" },
        seed_aa,
        if d.len() >= 57 { "yes" } else { "no" }
    );
}

/// Parsed `CONNECT_IND` LLData — everything needed to follow the connection onto
/// the data channels. Time fields keep their on-air units: `win_size`,
/// `win_offset`, `interval` are in 1.25 ms steps; `timeout` in 10 ms steps.
#[derive(Clone, Copy)]
pub struct ConnSpec {
    pub aa: u32,
    pub crc_init: u32,
    pub win_size: u8,
    pub win_offset: u16,
    pub interval: u16,
    pub latency: u16,
    pub timeout: u16,
    pub chm: [u8; 5],
    pub hop: u8,
    pub sca: u8,
    /// ChSel from the PDU header: the link hops with Channel Selection
    /// Algorithm #2 rather than #1.
    ///
    /// The initiator sets this bit only when the advertiser also advertised
    /// CSA#2 support, so the one bit in the `CONNECT_IND` header decides the
    /// algorithm for the whole connection. `hop` still carries a value in
    /// 5..=16 either way; CSA#2 leaves it unused.
    pub csa2: bool,
}

impl ConnSpec {
    /// Whether these LLData values are within the ranges the Core spec permits,
    /// i.e. whether this describes a connection that can actually be followed.
    ///
    /// Parsing a `CONNECT_IND` cannot fail on content — the fields are just
    /// bytes — so a corrupted reception yields a perfectly well-formed
    /// [`ConnSpec`] full of nonsense. Committing to one means scheduling the
    /// first event a minute into the future and holding the radio there, so the
    /// follower must range-check before it accepts the timeline.
    ///
    /// Ranges are Core v5.4 Vol 6 Part B §2.3.3.1 (`connInterval` 7.5 ms–4 s,
    /// `connSlaveLatency` ≤ 499, `connSupervisionTimeout` 100 ms–32 s and
    /// greater than `(1 + latency) × interval × 2`, `hopIncrement` 5–16,
    /// `transmitWindowSize` ≤ min(10 ms, interval − 1.25 ms)) plus §4.5.8.1's
    /// requirement of at least two used data channels.
    pub fn is_followable(&self) -> bool {
        let ch_count: u32 = self.chm.iter().map(|b| b.count_ones()).sum();
        // Units: interval/win_* are 1.25 ms steps, timeout is 10 ms steps, so
        // the timeout comparison is done in 1.25 ms steps (×8).
        (6..=3200).contains(&self.interval)
            && self.latency <= 499
            && (10..=3200).contains(&self.timeout)
            && (self.timeout as u32) * 8 > (1 + self.latency as u32) * (self.interval as u32) * 2
            && (5..=16).contains(&self.hop)
            && self.win_size >= 1
            && (self.win_size as u16) <= core::cmp::min(8, self.interval - 1)
            && self.win_offset <= self.interval
            && self.chm[4] & 0xE0 == 0 // bits 37..39 are RFU and must be zero
            && ch_count >= 2
            && access_address_valid(self.aa)
    }
}

/// Core v5.4 Vol 6 Part B §2.1.2 validity rules for a data-channel access
/// address. Cheap and worth applying: a random 32-bit value from a corrupted
/// reception fails these far more often than not, and following a bogus AA wedges
/// the receiver on an address nothing will ever transmit.
fn access_address_valid(aa: u32) -> bool {
    if aa == 0x8E89_BED6 {
        return false; // the advertising access address
    }
    let b = aa.to_le_bytes();
    if b[0] == b[1] && b[1] == b[2] && b[2] == b[3] {
        return false; // all four octets equal
    }
    // No more than six consecutive identical bits, and at least two transitions
    // in the six most significant bits.
    let mut run = 1u32;
    let mut msb_transitions = 0u32;
    for i in 1..32 {
        let prev = (aa >> (i - 1)) & 1;
        let cur = (aa >> i) & 1;
        if cur == prev {
            run += 1;
            if run > 6 {
                return false;
            }
        } else {
            run = 1;
            if i >= 27 {
                msb_transitions += 1;
            }
        }
    }
    msb_transitions >= 2
}

/// Parse a `CONNECT_IND` payload (`InitA[6] AdvA[6] LLData[22]`) into a
/// [`ConnSpec`]. `payload` starts at InitA (i.e. `buf[2..]`); needs ≥34 bytes.
/// `hdr` is the PDU header byte (`buf[0]`), which carries ChSel in bit 5.
pub fn parse_connect_ind(hdr: u8, payload: &[u8]) -> Option<ConnSpec> {
    if payload.len() < 34 { return None; }
    let ll = &payload[12..34]; // LLData
    Some(ConnSpec {
        aa: u32::from_le_bytes([ll[0], ll[1], ll[2], ll[3]]),
        crc_init: ll[4] as u32 | (ll[5] as u32) << 8 | (ll[6] as u32) << 16,
        win_size: ll[7],
        win_offset: u16::from_le_bytes([ll[8], ll[9]]),
        interval: u16::from_le_bytes([ll[10], ll[11]]),
        latency: u16::from_le_bytes([ll[12], ll[13]]),
        timeout: u16::from_le_bytes([ll[14], ll[15]]),
        chm: [ll[16], ll[17], ll[18], ll[19], ll[20]],
        hop: ll[21] & 0x1F,
        sca: ll[21] >> 5,
        csa2: hdr & 0x20 != 0,
    })
}

/// Decode a `CONNECT_IND` payload into labeled lines. Every field is plaintext —
/// the PDU is sent before the link is encrypted — and the LLData carries exactly
/// what a sniffer needs to follow the connection onto the data channels: Access
/// Address, CRCInit, channel map and hop increment, plus the link timing
/// parameters. `payload` starts at InitA (i.e. `buf[2..]`); needs ≥34 bytes.
/// `hdr` is the PDU header byte (`buf[0]`), the source of the ChSel bit.
pub fn decode_connect_ind(hdr: u8, payload: &[u8]) -> bool {
    use core::fmt::Write;
    let spec = match parse_connect_ind(hdr, payload) {
        Some(s) => s,
        None => return false,
    };
    let init = &payload[0..6];   // Initiator (the central) — on-air LE
    let adva = &payload[6..12];  // Advertiser (the peripheral) — on-air LE
    let ch_count: u32 = spec.chm.iter().map(|b| b.count_ones()).sum();

    // 1.25 ms units → hundredths of a ms (×125) for a "NN.MMms" render.
    let iv = spec.interval as u32 * 125;
    let ws = spec.win_size as u32 * 125;
    let wo = spec.win_offset as u32 * 125;

    let mut s: LogStr = LogStr::new();
    let _ = write!(s, "    InitA={:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X} -> AdvA={:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}",
        init[5], init[4], init[3], init[2], init[1], init[0],
        adva[5], adva[4], adva[3], adva[2], adva[1], adva[0]);
    emit(s);
    let mut s: LogStr = LogStr::new();
    // `csa` is the hop algorithm the pair will use — the field that says whether
    // the channel sequence follows `hop` at all.
    let _ = write!(s, "    AA=0x{:08X} CRCInit=0x{:06X} hop={} sca={} csa={}",
        spec.aa, spec.crc_init, spec.hop, spec.sca, if spec.csa2 { 2 } else { 1 });
    emit(s);
    let mut s: LogStr = LogStr::new();
    let _ = write!(s, "    interval={}.{:02}ms latency={} timeout={}ms",
        iv / 100, iv % 100, spec.latency, spec.timeout as u32 * 10);
    emit(s);
    let mut s: LogStr = LogStr::new();
    // ChM in spec octet order: chm[0] bit 0 is channel 0, so the leftmost hex
    // byte covers channels 0-7. This used to print chm[4]..chm[0] — reversed,
    // like a big-endian integer. It is self-consistent but reads exactly like
    // wire order, and it caused a live misdiagnosis: a capture showing
    // "0CF6C00000" was decoded by hand as channels {2,3,9,10,12,13,14,15,22,23}
    // when the follower was correctly hopping {22,23,25,26,28,29,30,31,34,35},
    // making a working channel map look like the bug.
    let _ = write!(s, "    winsize={}.{:02}ms winoffset={}.{:02}ms chmap={:02X}{:02X}{:02X}{:02X}{:02X} ({} ch)",
        ws / 100, ws % 100, wo / 100, wo % 100,
        spec.chm[0], spec.chm[1], spec.chm[2], spec.chm[3], spec.chm[4], ch_count);
    emit(s);
    true
}


// ── Extended advertising (BLE 5) decoder ─────────────────────────────────────
//
// ADV_EXT_IND and friends use the Common Extended Advertising Payload Format:
//   [ExtHdrLen:6 | AdvMode:2] [Extended Header] [AdvData]
// The extended header is a 1-byte flags field followed by the present fields in
// a fixed order, then optional ACAD. Fields we recognise are decoded; the rest
// (CTEInfo, SyncInfo, ACAD) are skipped, and any trailing AdvData is handed to
// the normal AD-structure decoder. When the walk cannot account for the whole
// payload it reports so via `ExtInfo::ok`, and the caller hex-dumps the raw
// bytes instead.
/// AuxPtr extracted from an extended-advertising header: where (data channel
/// index + PHY) and when (µs offset from the packet start) the aux packet airs.
/// `phy`: 0 = LE 1M, 1 = LE 2M, 2 = LE Coded.
pub struct AuxPtr {
    pub chan: u8,
    pub phy: u8,
    pub offset_us: u32,
}

/// SyncInfo extracted from an `AUX_ADV_IND` header: everything needed to receive
/// the advertiser's periodic advertising train (`AUX_SYNC_IND` + chained
/// `AUX_CHAIN_IND` on the data channels selected by CSA#2 on the periodic AA).
/// `offset_us == 0` means the offset was too far to represent → unschedulable.
#[derive(Clone, Copy)]
pub struct SyncInfo {
    pub offset_us: u32,     // to the AUX_SYNC_IND, from this packet's air-start
    pub interval_125us: u16, // periodic advertising interval, 1.25 ms units
    pub chm: [u8; 5],        // 37-bit periodic channel map
    pub aa: u32,             // periodic Access Address
    pub crc_init: u32,       // 24-bit CRCInit
    pub event_counter: u16,  // paEventCounter of the AUX_SYNC_IND the offset points to
}

/// Actionable fields the scanner needs from an extended-advertising header.
#[derive(Default)]
pub struct ExtInfo {
    pub aux: Option<AuxPtr>,
    pub adi: Option<u16>,
    pub sync: Option<SyncInfo>,
    /// Whether the walk accounted for the whole payload — header well-formed and
    /// any ACAD/AdvData decoded cleanly. Drives the caller's fall back to a raw
    /// hex dump. Only meaningful on the logging walk ([`decode_ext_adv`]); the
    /// silent walk ([`parse_ext_hdr`]) never touches AdvData and leaves it false.
    pub ok: bool,
}

/// Extract [`ExtInfo`] from an extended-advertising payload, silently.
///
/// Serves the sniffer's capture path, which needs the AuxPtr immediately — an aux
/// packet can air only ~300 µs later. [`decode_ext_adv`] prints the same header
/// later, off that path; both share one walker so the two agree.
pub fn parse_ext_hdr(p: &[u8]) -> ExtInfo {
    walk_ext_hdr(p, false)
}

/// Decode an extended-advertising payload, logging each header field and any
/// trailing AdvData, and return its [`ExtInfo`].
pub fn decode_ext_adv(p: &[u8]) -> ExtInfo {
    walk_ext_hdr(p, true)
}

/// Shared extended-header walk. `log` selects whether each recognised field is
/// also emitted; the returned [`ExtInfo`] is identical either way.
fn walk_ext_hdr(p: &[u8], log: bool) -> ExtInfo {
    use core::fmt::Write;
    let mut info = ExtInfo::default();
    if p.is_empty() { return info; }

    let ext_hdr_len = (p[0] & 0x3F) as usize;
    if log {
        let adv_mode = match p[0] >> 6 {
            0 => "non-conn/non-scan",
            1 => "connectable",
            2 => "scannable",
            _ => "rfu",
        };
        let mut s: LogStr = LogStr::new();
        let _ = write!(s, "  ExtHdr: mode={} hdrlen={}\r\n", adv_mode, ext_hdr_len);
        emit(s);
        // Provisionally decoded; the ACAD/AdvData walks below can revoke it, as
        // can a header claiming more bytes than the packet holds.
        // The header ends at `1 + ext_hdr_len`; that must be inside the packet.
        info.ok = ext_hdr_len < p.len();
    }

    // Walk the extended header fields when present (ext_hdr_len covers the flags
    // byte + fields + ACAD; AdvData starts at 1 + ext_hdr_len).
    if ext_hdr_len >= 1 && p.len() > 1 {
        let flags = p[1];
        let mut off = 2;

        // AdvA (6 bytes, little-endian on air).
        if flags & 0x01 != 0 && off + 6 <= p.len() {
            if log {
                let a = &p[off..off + 6];
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr AdvA: {:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}\r\n",
                    a[5], a[4], a[3], a[2], a[1], a[0]);
                emit(s);
            }
            off += 6;
        }
        // TargetA (6 bytes).
        if flags & 0x02 != 0 && off + 6 <= p.len() {
            if log {
                let a = &p[off..off + 6];
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr TargetA: {:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}\r\n",
                    a[5], a[4], a[3], a[2], a[1], a[0]);
                emit(s);
            }
            off += 6;
        }
        // CTEInfo (1 byte): CTE Time (bits 0-4, 8µs units) + CTE Type (bits 6-7).
        if flags & 0x04 != 0 && off < p.len() {
            if log {
                let cte = p[off];
                let time_us = (cte & 0x1F) as u32 * 8;
                let typ = match (cte >> 6) & 0x03 {
                    0 => "AoA",
                    1 => "AoD-1us",
                    2 => "AoD-2us",
                    _ => "rfu",
                };
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr CTEInfo: type={} time={}us\r\n", typ, time_us);
                emit(s);
            }
            off += 1;
        }
        // ADI (2 bytes): DID (low 12 bits) + SID (high 4 bits).
        if flags & 0x08 != 0 && off + 2 <= p.len() {
            let adi = u16::from_le_bytes([p[off], p[off + 1]]);
            info.adi = Some(adi);
            if log {
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr ADI: did=0x{:03X} sid=0x{:X}\r\n",
                    adi & 0x0FFF, adi >> 12);
                emit(s);
            }
            off += 2;
        }
        // AuxPtr (3 bytes): channel, offset units/value, and PHY of the aux packet.
        if flags & 0x10 != 0 && off + 3 <= p.len() {
            let chan    = p[off] & 0x3F;
            let units   = if p[off] & 0x80 != 0 { 300u32 } else { 30 }; // µs
            let raw     = u16::from_le_bytes([p[off + 1], p[off + 2]]);
            let aux_off = (raw & 0x1FFF) as u32 * units;
            let phy_num = (p[off + 2] >> 5) & 0x07;
            info.aux = Some(AuxPtr { chan, phy: phy_num, offset_us: aux_off });
            if log {
                let phy = match phy_num {
                    0 => "1M", 1 => "2M", 2 => "Coded", _ => "?",
                };
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr AuxPtr: ch={} phy={} offset={}us\r\n",
                    chan, phy, aux_off);
                emit(s);
            }
            off += 3;
        }
        // SyncInfo (18 bytes, all little-endian): the periodic advertising sync
        // parameters (Core v5.4 Vol 6 Part B §2.3.4.6).
        if flags & 0x20 != 0 && off + 18 <= p.len() {
            let si = &p[off..off + 18];
            let w0 = u16::from_le_bytes([si[0], si[1]]);
            let sync_off = (w0 & 0x1FFF) as u32; // SyncPacketOffset (0 = too far)
            let units = if w0 & 0x2000 != 0 { 300u32 } else { 30 }; // OffsetUnits
            let adjust = if w0 & 0x4000 != 0 { 2_457_600u32 } else { 0 }; // OffsetAdjust
            let offset_us = if sync_off == 0 { 0 } else { sync_off * units + adjust };
            let interval_125us = u16::from_le_bytes([si[2], si[3]]);
            let chm = [si[4], si[5], si[6], si[7], si[8] & 0x1F];
            let sca = (si[8] >> 5) & 0x07;
            let aa = u32::from_le_bytes([si[9], si[10], si[11], si[12]]);
            let crc_init = u32::from_le_bytes([si[13], si[14], si[15], 0]);
            let event_counter = u16::from_le_bytes([si[16], si[17]]);
            info.sync = Some(SyncInfo {
                offset_us, interval_125us, chm, aa, crc_init, event_counter,
            });
            if log {
                let ms_x100 = interval_125us as u32 * 125;
                let mut s: LogStr = LogStr::new();
                let _ = write!(s,
                    "  ExtHdr SyncInfo: aa=0x{:08X} crcinit=0x{:06X} interval={}.{:02}ms offset={}us evt={} sca={} chm={:02X}{:02X}{:02X}{:02X}{:02X}\r\n",
                    aa, crc_init, ms_x100 / 100, ms_x100 % 100, offset_us, event_counter,
                    sca, chm[0], chm[1], chm[2], chm[3], chm[4]);
                emit(s);
            }
            off += 18;
        }
        // TxPower (1 byte, signed dBm).
        if flags & 0x40 != 0 && off < p.len() {
            if log {
                let mut s: LogStr = LogStr::new();
                let _ = write!(s, "  ExtHdr TxPower: {} dBm\r\n", p[off] as i8);
                emit(s);
            }
            off += 1;
        }

        // ACAD (Additional Controller Advertising Data): whatever remains between
        // the last present field and AdvData is a run of AD structures (BIGInfo,
        // ChannelMapUpdateInd…). Decode it the same way as AdvData.
        let hdr_end = 1 + ext_hdr_len;
        if log && off < hdr_end && hdr_end <= p.len() {
            let acad = &p[off..hdr_end];
            let mut s: LogStr = LogStr::new();
            let _ = write!(s, "  ExtHdr ACAD ({} B):\r\n", acad.len());
            emit(s);
            info.ok &= log_ad_structures(acad, None, true) == acad.len();
        }
    }

    // AdvData (standard AD structures) follows the extended header.
    let adv_data_start = 1 + ext_hdr_len;
    if log && adv_data_start < p.len() {
        // Ext-adv AdvA lives in the extended header (not at a fixed payload
        // offset), so the own-address check is not applied here.
        let adv_data = &p[adv_data_start..];
        info.ok &= log_ad_structures(adv_data, None, true) == adv_data.len();
    }

    info
}
